describe('Redmine Tests', function () {
  
	context('Users Tests', function(){

		it('create user', function(){
			cy.visit('http://demo.redmine.org')
			cy.get('.register').click()
			cy.url().should('match', /register/)
			cy.get('#user_login').type('userTest')
			cy.get('#user_password').type('pass')
			cy.get('#user_password_confirmation').type('pass')
			cy.get('#user_firstname').type('User')
			cy.get('#user_lastname').type('Tester')
			cy.get('#user_mail').type('userTest@userTest.com')
			cy.get('#user_language').select('Portuguese (Português)')
			cy.get('[type="submit"]').click()
			cy.url().should('match', /account/)
		})
	})

	context('Projects Test', function(){

		it('create project', function(){
			cy.loginByUI()
			cy.get('a.projects').click()
			cy.get('a.icon-add').click()
			cy.get('#project_name').type('SoftboxTestt')
			cy.get('#project_description').type('vaga para desenvolvedora de automação de testes')
			cy.get('#project_trackers > :nth-child(3) > input').click()
			cy.get('#project_trackers > :nth-child(4) > input').click()
			cy.get('[name="commit"]').click()
		})
	})

	context('Issues Test', function(){

		it('create news issue', function(){
			cy.loginByUI()
			cy.get('a.projects').click()
			cy.get('#q').type('Softbox{enter}')
			cy.visit('http://demo.redmine.org/projects/softboxtestt')
			cy.get('.new-issue').click()
			cy.get('#issue_subject').type('Issue 1')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 2')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 3')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 4')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 5')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 6')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 7')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 8')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 9')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 10')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 11')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 12')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 13')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 14')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 15')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 16')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 17')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 18')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 19')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 20')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 21')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 22')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 23')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 24')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 25')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 26')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 27')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 28')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 29')
			cy.get('[name="continue"]').click()
			cy.get('#issue_subject').type('Issue 30')
			cy.get('[name="continue"]').click()

			// cy.get('ul>li').each(function () {
			// 	cy.fixture('issue').should((issue) => {
			// 		expect(users[0].name).to.exist
	  //     			expect(validIssue.issue_tracker_id).to.eq('Bug')
	  //     			expect(validIssue.issue_subject).to.eq('Issue 29')
	  //     			expect(validIssue.issue_status_id).to.eq('New')
	  //     			expect(validIssue.issue_priority_id).to.eq('Urgent')
   //  			})
			// })
		})

		it('valid issue 29', function(){
			cy.get('.issues').click()
			cy.url().should('match', /issues/)
			cy.get('#add_filter_select').select('Subject')
			cy.contains('Issue 29').click()
			cy.get('.subject > div > h3').should('contain', 'Issue 29')
			cy.get('td.status').should('contain', 'New')
			cy.get('td.priority').should('contain', 'Normal')
			cy.get('.next').click()
			
			// cy.fixture('validIssue.json').should((validIssue) => {
   //    			expect(validIssue.issue_subject).to.eq('Issue 29')
   //    			expect(validIssue.issue_status_id).to.eq('New')
   //    			expect(validIssue.issue_priority_id).to.eq('Urgent')
   //  		})
		})
	})
})